services:
  - type: web
    name: flipkart-sample44-backend
    runtime: docker
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    healthCheckPath: /health.php
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_CHARSET
        sync: false
      - key: APP_BASE_URL
        sync: false
